### ISSUE TITLE
IPA is not saved in var/mobile/DumpIpa

### ISSUE THREAD

**Issue by Kcion** [wh1te4ever/TrollDecryptor#1]
iOS 16,4.1, a14 installed with trollstore

how to reproduce

- open CocoaTop and find pic of process
- Put pid at the top
- Press decrypt
- Says success!
- Open Filza, and there is a new folder called “DumpIpa”
- Nothing in the folder
![Uploading IMG_2259.png…]()

![IMG_2260](https://github.com/wh1te4ever/TrollDecryptor/assets/152314849/099a2c35-bccb-4e34-82fb-0cd9549cbc16)

**Comment by augustobob** [comment]
It says the ipa is saved on /tmp, maybe opening the share sheet or saving into an accessible folder from files app would suit better
![IMG_1395](https://github.com/wh1te4ever/TrollDecryptor/assets/41238825/bfbb7bf4-40d6-461d-a8c7-f85e66f45202)

**Comment by QuanTrieuPCYT** [comment]
lol i don't know this issue even exists. After decrypting the app I just opened Apps Manager in Filza, head over to the trolldecryptor app and the IPAs will be in the Documents folder

**Comment by Kcion** [comment]
Thanks for the feedback, turns out var/mobile/dumpipa was created when I was using a different decrypting software.

**Comment by augustobob** [comment]
@wh1te4ever updated the readme with the location the files are located. You can get the decrypted ipa with filza
